apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-files-configmap
data:
  {{ $files := .Files }}
  {{- range tuple "foo/config1.toml" "foo/config2.toml" "foo/config3.toml" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{ end }}